# Generated by Django 5.2 on 2025-05-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackapi', '0003_answervote_answer_voters_questionvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(default=[], max_length=200),
            preserve_default=False,
        ),
    ]
