# Generated by Django 5.2 on 2025-05-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackapi', '0004_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
